apiVersion: v2
name: discourse
description: A Helm chart for deploying Discourse forum software on Kubernetes

type: application

version: 3.4.0
appVersion: "3.4.3"

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "20.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
