apiVersion: v2
name: filesender
description: A Helm chart for FileSender 3.x - secure file sharing platform
type: application
version: 0.1.0
appVersion: "3.3"
keywords:
  - filesender
  - file-sharing
  - saml
  - simplesamlphp
home: https://filesender.org
sources:
  - https://github.com/filesender/filesender
  - https://github.com/mecmus/helm-charts
maintainers:
  - name: mecmus
