apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}-smtp
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.discourse.smtp.enabled }}
data:
  username: {{ .Values.discourse.smtp.username | b64enc | quote }}
  password: {{ .Values.discourse.smtp.password | b64enc | quote }}
{{- end }}
---
{{- if .Values.discourse.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}-s3
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.discourse.s3.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.discourse.s3.secretAccessKey | b64enc | quote }}
{{- end }}
---
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}-postgresql-external
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.externalPostgresql.password | b64enc | quote }}
{{- end }}
