apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  {{- if not .Values.postgresql.auth.existingSecret }}
  postgres-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- if not .Values.externalDatabase.existingSecret }}
  database-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  {{- if and .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
  redis-password: {{ .Values.redis.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- if and .Values.externalRedis.password (not .Values.externalRedis.existingSecret) }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not .Values.discourse.smtp.existingSecret }}
  smtp-password: {{ .Values.discourse.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.discourse.s3.enabled (not .Values.discourse.s3.existingSecret) }}
  s3-access-key-id: {{ .Values.discourse.s3.accessKeyId | b64enc | quote }}
  s3-secret-access-key: {{ .Values.discourse.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
