apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "discourse.serviceAccountName" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.automount }}
automountServiceAccountToken: true
{{- end }}
