{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.fastcgi.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filesender.fullname" . }}-fastcgi-params
  labels:
    {{- include "filesender.labels" . | nindent 4 }}
data:
  SCRIPT_FILENAME: "/var/www/html/www$fastcgi_script_name"
  QUERY_STRING: "$query_string"
  REQUEST_METHOD: "$request_method"
  CONTENT_TYPE: "$content_type"
  CONTENT_LENGTH: "$content_length"
  SCRIPT_NAME: "$fastcgi_script_name"
  REQUEST_URI: "$request_uri"
  DOCUMENT_URI: "$document_uri"
  DOCUMENT_ROOT: "/var/www/html/www"
  SERVER_PROTOCOL: "$server_protocol"
  REQUEST_SCHEME: "$scheme"
  HTTPS: "$https"
  GATEWAY_INTERFACE: "CGI/1.1"
  SERVER_SOFTWARE: "nginx"
  REMOTE_ADDR: "$remote_addr"
  REMOTE_PORT: "$remote_port"
  SERVER_ADDR: "$server_addr"
  SERVER_PORT: "$server_port"
  SERVER_NAME: "$server_name"
  REDIRECT_STATUS: "200"
{{- end }}
{{- end }}
