{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filesender.fullname" . }}-postgresql
  labels:
    {{- include "filesender.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
