{{- if and (eq .Values.filesender.auth.type "oidc") (not .Values.filesender.auth.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filesender.fullname" . }}-oidc
  labels:
    {{- include "filesender.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-client-id: {{ .Values.filesender.auth.oidc.clientId | quote }}
  oidc-client-secret: {{ .Values.filesender.auth.oidc.clientSecret | quote }}
{{- end }}
