{{- if .Values.postgresql.internal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filesender.fullname" . }}-postgresql
  labels:
    {{- include "filesender.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.internal.password | default (randAlphaNum 32) | quote }}
{{- end }}
