apiVersion: v1
kind: Service
metadata:
  name: {{ include "filesender.fullname" . }}
  labels:
    {{- include "filesender.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.nginx.enabled }}
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: phpfpm
      protocol: TCP
      name: phpfpm
    {{- end }}
  selector:
    {{- include "filesender.selectorLabels" . | nindent 4 }}
