apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odk-central.fullname" . }}-redis-cache-config
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
data:
  redis.conf: |
    save 3600 1
    dbfilename enketo-cache.rdb
    dir /data
    port 6380
