apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odk-central.fullname" . }}-redis-main-config
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
data:
  redis.conf: |
    save 300 1
    dbfilename enketo-main.rdb
    dir /data
