apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odk-central.fullname" . }}-nginx
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "odk-central.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "odk-central.labels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DOMAIN
              value: {{ .Values.domain | quote }}
            - name: SSL_TYPE
              value: "upstream"
            - name: HTTPS_PORT
              value: {{ .Values.httpsPort | quote }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
