apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odk-central.fullname" . }}-postgres
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  {{- end }}
