apiVersion: v1
kind: Service
metadata:
  name: {{ include "odk-central.enketoRedisMainHost" . }}
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
    app.kubernetes.io/component: enketo-redis-main
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "odk-central.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: enketo-redis-main
