apiVersion: v1
kind: Service
metadata:
  name: {{ include "odk-central.fullname" . }}-enketo
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
    app.kubernetes.io/component: enketo
spec:
  type: ClusterIP
  ports:
    - port: 8005
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odk-central.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: enketo
